### ISSUE TITLE
Check still fails when PR comment edited

### ISSUE THREAD

**Issue by alex3236** [RoryQ/checkmate#15]
```
panic: interface conversion: interface {} is nil, not map[string]interface {}

goroutine 1 [running]:
github.com/roryq/checkmate/pkg/checkmate.getPullRequestBody(...)
	/home/runner/work/checkmate/checkmate/pkg/checkmate/action.go:75
github.com/roryq/checkmate/pkg/checkmate.Run({0x87f3f0, 0xc000096000}, 0xc00009a738, 0xc0000a8360?, 0x7effe06e63b8?)
	/home/runner/work/checkmate/checkmate/pkg/checkmate/action.go:39 +0x[44](https://github.com/alex3236/test/actions/runs/4259534064/jobs/7411846810#step:3:45)b
main.run()
	/home/runner/work/checkmate/checkmate/main.go:33 +0xed
main.main()
	/home/runner/work/checkmate/checkmate/main.go:37 +0x19
```

Workflow is still the same as mentioned in #13 
Seems that it can't get the pull request body for checking :(

**Comment by RoryQ** [comment]
I saw that too, this looks to be a different issue now - where the action is running on any `issue_comment` event, not just those on a PR. I'll fix this one too

**Comment by RoryQ** [comment]
Hopefully no more similar issues.
